modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
issueTrackerURL = "https://github.com/MCTeamPotato/Opotato/issues"

[[mods]]
modId = "opotato"
version = "${file.jarVersion}"
displayName = "Opotato"
authors="Team Potato"
description = '''
Yeah another optimization mod.
'''