modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
issueTrackerURL = "https://github.com/MCTeamPotato/PotatOptimize/issues"

[[mods]]
modId = "potatoptimize"
version = "${version}"
displayName = "PotatOptimize"
authors="Space Walker, Team Potato"
description = '''
n efficient and non-locational redstone dust implementation.
'''