modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPL-v3"

[[mods]]
modId = "opotato"
version = "${version}"
displayName = "Opotato"
authors = "TeamPotato"
description = '''
A Minecraft mod.
'''