modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU LESSER GENERAL PUBLIC LICENSE Version 3"
issueTrackerURL = "https://github.com/MCTeamPotato/Opotato/issues"

[[mods]]
modId = "opotato"
version = "${file.jarVersion}"
displayName = "Opotato"
authors="Team Potato"
description = '''
Not just an optimization mod.
'''